---
apiVersion: v1
kind: Service
metadata:
  name: redis-app-service
  labels: 
    author: madhav
spec:
  type: ClusterIP
  selector:
    name: redis-app
  ports:
  - port: 6379
    targetPort: 6379
...
