---
apiVersion: v1
kind: Service
metadata:
  name: result-app-service
  labels: 
    author: madhav
spec:
  type: LoadBalancer
  selector:
    name: result-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30009
...
