---
apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
  labels: 
    author: madhav
spec:
  type: LoadBalancer
  selector:
    name: voting-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30008
...
